title: '<a href="https://www.filamentgroup.com" class="project-logo">Filament Group</a> <span>collapse</span>'
description: A simple, accessible collapse dialog web component
theme: jekyll-theme-cayman
show_downloads: true
